name: Update Crypto Data

# Menjalankan workflow secara otomatis setiap 6 menit
# dan juga bisa dijalankan secara manual dari tab Actions
on:
  schedule:
    # Menggunakan cron untuk menjadwalkan run setiap 6 menit
    - cron: '*/6 * * * *'
  workflow_dispatch:

# Tambahkan blok permissions ini untuk memberikan izin tulis
permissions:
  contents: write

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          # Token ini sekarang akan memiliki izin yang cukup karena blok di atas
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas

      - name: Run data fetching script
        # Jalankan skrip Python yang sudah direvisi
        run: python cleaning/data_cleaner_and_puller.py
        env:
          # Pastikan Anda telah menambahkan secret ini di Settings > Secrets
          CMC_PRO_API_KEY: ${{ secrets.CMC_PRO_API_KEY }}

      - name: Commit and push changes
        # Action ini akan secara otomatis mendeteksi perubahan file dan membuat commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Automated update of top 100 crypto data"
          # Hanya commit file updated_file.csv
          file_pattern: 'cleaning/updated_file.csv'
