# Nama workflow Anda
name: Automated Data Update

# Memicu workflow pada push ke branch utama
on:
  push:
    branches:
      - main
  # Juga bisa dijadwalkan
  # schedule:
  #   - cron: '0 * * * *'

# Ini adalah blok yang harus Anda tambahkan atau perbarui
permissions:
  contents: write # Ini memberikan izin tulis ke bot untuk file repositori

# Definisikan jobs yang akan dijalankan
jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests

      - name: Run python cleaning script
        env:
          CMC_PRO_API_KEY: ${{ secrets.CMC_PRO_API_KEY }}
        run: |
          python cleaning/data_cleaner_and_puller.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add cleaning/cleaned_data.csv
          git commit -m "Automated data update" || echo "No changes to commit"
          git push
